name: metashark
description: MetaShark MLM app
publish_to: 'none'
version: 1.0.28+146

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  cupertino_icons: ^1.0.4
  url_launcher: ^6.0.20
  share_plus: ^4.0.4
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  shared_preferences: ^2.0.13
  animations: ^2.0.2
  modal_bottom_sheet: ^2.0.1
  faker: ^2.0.0
  my_commons:
    git: https://github.com/roipeker/my_commons.git
  flutter_native_splash: ^2.1.6
  recase: ^4.0.0
  go_router: ^3.0.7
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  rive: ^0.8.4
  package_info_plus: ^1.4.2
  flip_card: ^0.6.0
  dotted_decoration: ^2.0.0
  layout: ^1.0.2
  transparent_image: any
  video_player: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  image_res: ^0.3.0
  flutter_lints: ^1.0.4
  flutter_app_name: ^0.1.1

flutter:
  uses-material-design: true
  assets:
    #    - assets/i18n/
    - assets/images/
    - assets/images/languages/
    - assets/svgs/
    - assets/svgs/cryptos/
    - assets/svgs/icons/
    - assets/rive/
    - assets/images/mockup/
    - assets/animated/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/App-Icons.ttf?v=6
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
    #    - family: Roboto
    #      fonts:
    #        - asset: assets/fonts/Roboto-Regular.ttf
    #          weight: 400
    #        - asset: assets/fonts/Roboto-Medium.ttf
    #          weight: 500
    #        - asset: assets/fonts/Roboto-Bold.ttf
    #          weight: 700
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#          weight: 600
#      fonts:
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#    - family: AppIcons
#      fonts:
#        - asset: assets/fonts/AppIcons.ttf

## ---

### run with:
### flutter pub run flutter_launcher_icons:main
flutter_icons:
  # image_path: "assets/icon/ios.png"
  image_path_ios: "assets/icon/app_icon_1024.png"
  android: "ic_launcher" # can specify file name here e.g. "ic_launcher"
  ios: "Icon-App" # can specify file name here e.g. "My-Launcher-Icon"
  image_path_android: "assets/icon/app_icon_1024.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/app_icon_back.png"
  adaptive_icon_foreground: "assets/icon/app_icon_front.png"

### run with:
### flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#F8F8F8"
  #  background_image: assets/icon/splash_bg.png
  image: assets/icon/splash_logo.png
  #  branding_mode: center
  ios_content_mode: center
  android_gravity: center
  fullscreen: false
  android_disable_fullscreen: true

### Temporarily using spider to generate assets/ paths as const
### To install:
### `dart pub global activate spider`
### When you update files in /assets/** update [spider.yaml] accordingly if needed and run
### `spider build`


## to rename images (image_res):
# flutter packages pub run image_res:main run

## change app name:
# flutter pub run flutter_app_name
flutter_app_name:
  name: "Meta Shark"

## change bundle id:
# flutter pub run change_app_package_name:main com.roipeker.metashark.test

## run on webserver to test on devices in network:
# flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0

### icon_font_generator: (for web)
# install: pub global activate icon_font_generator
# icon_font_generator --from=assets/src/my_icons/ --class-name=SharkIcons --out-font=assets/fonts/Shark-Icons.ttf --out-flutter=lib/data/shark_icons.dart
# woff2_compress assets/fonts/Shark-Icons.ttf